language: c++
compiler:
 - gcc
 - clang

sudo: required
dist: trusty
addons:
  apt:
    packages:
      - doxygen
      - graphviz
      - qt5-default
      - tree

script:
 - tree
 - mkdir build
 - cd build
 - cmake -DCMAKE_INSTALL_PREFIX=/usr ..
 - make doc
 - sudo make install
 - cd ../examples/simple
 - cmake .
 - make
 
