language: c++
sudo: required
dist: precise

addons:
    ssh_known_hosts: msrd0.duckdns.org
    apt:
        sources:
         - sourceline: 'ppa:george-edison55/precise-backports'
         - sourceline: 'ppa:immerrr-k/qt5-backports'
         - sourceline: 'ppa:ubuntu-toolchain-r/test'
         - sourceline: 'deb [arch=amd64] https://msrd0.duckdns.org/debian/ precise main'
           key_url: 'https://msrd0.duckdns.org/debian/key.asc'
        packages:
         - apt-utils
         - cmake-data
         - cmake
         - debhelper
         - doxygen
         - dpkg-dev
         - g++-5
         - gcc-5
         - graphviz
         - pkg-config
         - qtchooser
         - qt5-default
         - sshfs

before_script:
  - dig +short myip.opendns.com @resolver1.opendns.com
  - openssl aes-256-cbc -K $encrypted_f039ccdac5d1_key -iv $encrypted_f039ccdac5d1_iv -in .travis-keys.tar.xz.enc -out .travis-keys.tar.xz -d
  - tar xfa .travis-keys.tar.xz
  - mv alarmpi-debian* ~/.ssh/
  - touch ~/.ssh/config
  - echo "Host msrd0.duckdns.org" >>~/.ssh/config
  - echo "  IdentityFile ~/.ssh/alarmpi-debian" >>~/.ssh/config
  - export CC=/usr/bin/gcc-5
  - export CXX=/usr/bin/g++-5


script:
  - version=$(cat debian/changelog | grep -E '^qsl \(.+\) precise' | head -n1 | tr -d '(' | tr '-' ' ' | awk '{print $2}')
  - echo "QSL $version"
  - wget "https://github.com/msrd0/QSL/archive/v${version}.tar.gz"
  - tar xfz "v${version}.tar.gz"
  - ls -l
  - pushd "QSL-${version}"
  - cp -R ../debian .
  - dpkg-buildpackage -us -uc
  - popd
  - ls *qsl*

after_success:
  - make
  - test -d mount && sudo umount mount || true

after_script:
  - rm ~/.ssh/alarmpi-debian*
