sudo: required
dist: trusty
service:
 - docker

before_script:
 - export reponame=`basename $PWD`
 - pushd ..
 - sudo docker build -t qsl-ubuntu -f $reponame/docker/ubuntu/Dockerfile .
 - popd
script:
 - sudo docker run qsl-ubuntu
 
