sudo: required
dist: trusty
service:
 - docker

before_script:
 - export reponame=`basename $PWD`
 - pushd ..
 - sed -i "s/@spis@/$reponame/" $reponame/docker/ubuntu/Dockerfile
 - sudo docker build -t spis-ubuntu -f $reponame/docker/ubuntu/Dockerfile .
 - popd
script:
 - sudo docker run spis-ubuntu
 
